### ISSUE TITLE
VPN Support

### ISSUE THREAD

**Issue by Johnnei** [Johnnei/JavaTorrent#50]
Add support to the various modules to run the torrent client on a manually configured VPN.

- [ ] Add options to configure the VPN
- [ ] Add options to the `ISocket` interface to indicate whether VPN works
- [ ] Ensure that the 'sender' field works properly for Trackers over VPN'd connections
- [ ] Ensure that the connecting to peers works properly over VPN'd connections.

As requested by @robertalpha

**Comment by robertalpha** [comment]
Awesome!
